---
# vars file for JupyterHubJJ
# jjpH adaptacion desde https://github.com/jenkstom/ansible-jupyterhub/blob/master/vars/main.yml
jupyter_pkgs:
  - git
  - nodejs-legacy
  - npm
  - python
  - python-dev
  - python-setuptools
  - python3
  - python3-dev
  - python3-pip
  - python3-setuptools
  - sudo
  - apt-transport-https

